### ISSUE TITLE
count(): Argument #1 ($value) must be of type Countable|array, null given

### ISSUE THREAD

**Issue by 89z** [socialAPIS/YoutubeDownloader#10]
Using this program:

~~~php
<?php
require_once '../vendor/autoload.php';
$yt = new \YoutubeDownloader\YoutubeDownloader();
$registrationResponse = $yt->registerDevice();
~~~

I get this result:

~~~
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:67
Stack trace:
#0 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(67): count(NULL)
#1 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(107): GuzzleHttp\Handler\CurlFactory->release(Object(GuzzleHttp\Handler\EasyHandle))
#2 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Client.php(268): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Client.php(129): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 D:\Desktop\etc\vendor\socialapis\youtubedownloader\src\Request.php(164): GuzzleHttp\Client->request('POST', 'https://youtube...', Array)
#14 D:\Desktop\etc\vendor\socialapis\youtubedownloader\src\Request.php(206): YoutubeDownloader\Request->request('POST', 'https://youtube...', NULL)
#15 D:\Desktop\etc\vendor\socialapis\youtubedownloader\src\Request\DeviceRegistrationRequest.php(28): YoutubeDownloader\Request->post()
#16 D:\Desktop\etc\vendor\socialapis\youtubedownloader\src\YoutubeDownloader.php(111): YoutubeDownloader\Request\DeviceRegistrationRequest->deviceregistration()
#17 D:\Desktop\etc\vendor\FetchPlayer.php(17): YoutubeDownloader\YoutubeDownloader->registerDevice()
#18 {main}
  thrown in D:\Desktop\etc\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67
~~~

**Comment by 89z** [comment]
as a workaround, it seem just commenting out the block around here fixes it:

~~~
vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:67
~~~
